# Generated by Django 5.0.3 on 2024-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
