# Generated by Django 5.0.3 on 2024-03-09 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exercise_types',
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'SUNDAY'), ('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY')], max_length=30)),
            ],
            options={
                'db_table': 'workout_days',
            },
        ),
        migrations.CreateModel(
            name='WorkoutGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'workout_goals',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('reccomendation', models.CharField(blank=True, max_length=500, null=True)),
                ('repetition', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=500, null=True)),
                ('rest_period', models.CharField(blank=True, max_length=500, null=True)),
                ('walk', models.CharField(blank=True, max_length=500, null=True)),
                ('achievement', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.exercisetype')),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(related_name='workout_plans', to='workout.exercise')),
                ('workout_days', models.ManyToManyField(related_name='workout_plans', to='workout.workoutday')),
                ('workout_goals', models.ManyToManyField(related_name='workout_plans', to='workout.workoutgoal')),
            ],
            options={
                'db_table': 'workout_plans',
            },
        ),
    ]
