# Generated by Django 5.0.3 on 2024-03-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
